const etdr = require('eslint-plugin-etdr')

module.exports = [
  ...etdr.recommendedNextConfigs,
  {
    ignores: [
      'src/components/ui/*', // folder is generated by shadcn
      '**/licenses.ts',
    ],
  },
  {
    files: ['src/components/*'],
    rules: {
      '@typescript-eslint/no-shadow': 'off',
    },
  },
]
